language: python

python:
  - "3.5"

install:
  - curl -sSL "https://get.docker.com/gpg" | sudo -E apt-key add -
  - sudo apt-get update -o Dpkg::Options::="--force-confold" --assume-yes install docker-engine
  - docker version
  - sudo pip install docker-compose
  - docker-compose version
  - pip install -r requirements.txt

before_script:
  - docker-compose -f dev-docker-compose.yml up --build -d

script:
  - pytest --verbose

after_script:
  - docker-compose -f dev-docker-compose.yml down