version: '2.1'

services:
  db_movie_tracker:
    container_name: db_movie_tracker
    image: postgres:10.1-alpine
    restart: on-failure
    healthcheck:
      test: "pg_isready -d test_db -h 127.0.0.1 -p 5432 -U admin"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  app_movie_tracker:
    container_name: app_movie_tracker
    build: .
    depends_on:
      db_movie_tracker:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://admin:admin@db_movie_tracker:5432/test_db
      - FLASK_CONFIGURATION=testing
    ports:
      - "5001:5001"


